-- Barmer Food Delivery production schema
-- Firebase Authentication is the sole application identity provider.
-- Supabase is used for PostgreSQL, Data API, Storage, Realtime and Edge Functions.
create extension if not exists pgcrypto;
do $$ begin create type public.app_role as enum ('customer','restaurant','rider','admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.application_status as enum ('pending','approved','rejected','suspended'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('placed','restaurant_notified','accepted','preparing','ready_for_pickup','rider_assigned','picked_up','on_the_way','delivered','cancelled'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles(id uuid primary key, firebase_uid text unique, full_name text not null, phone text unique, role public.app_role not null default 'customer', avatar_url text, address text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.restaurant_applications(id uuid primary key default gen_random_uuid(),applicant_id uuid,restaurant_name text not null,owner_name text not null,phone text not null,address text not null,barmer_area text not null,registration_no text,status public.application_status not null default 'pending',admin_note text,reviewed_by uuid,reviewed_at timestamptz);
create table if not exists public.rider_applications(id uuid primary key default gen_random_uuid(),applicant_id uuid,full_name text not null,phone text not null,address text not null,vehicle_no text,licence_no text,emergency_contact text,status public.application_status not null default 'pending',admin_note text,reviewed_by uuid,reviewed_at timestamptz);
create table if not exists public.restaurants(id uuid primary key default gen_random_uuid(),owner_id uuid,name text not null,cuisine text,address text not null,area text not null,phone text,rating numeric(2,1) default 0,delivery_fee numeric(10,2) default 0,is_open boolean default false,is_approved boolean not null default false,latitude double precision,longitude double precision,created_at timestamptz not null default now());
create table if not exists public.menu_categories(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null,sort_order int default 0);
create table if not exists public.menu_items(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,category_id uuid references public.menu_categories(id) on delete set null,name text not null,description text,price numeric(10,2) not null,image_url text,is_available boolean default true);
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),customer_id uuid not null,restaurant_id uuid not null references public.restaurants(id) on delete restrict,rider_id uuid,status public.order_status not null default 'placed',delivery_address text not null,delivery_latitude double precision,delivery_longitude double precision,subtotal numeric(10,2) not null,delivery_fee numeric(10,2) not null default 0,total numeric(10,2) not null,payment_method text not null default 'cod',created_at timestamptz not null default now(),accepted_at timestamptz,picked_up_at timestamptz,delivered_at timestamptz);
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,menu_item_id uuid references public.menu_items(id) on delete set null,item_name text not null,quantity int not null check(quantity>0),unit_price numeric(10,2) not null);
create table if not exists public.rider_locations(rider_id uuid primary key,latitude double precision not null,longitude double precision not null,accuracy_m double precision,heading double precision,is_online boolean not null default false,updated_at timestamptz not null default now());
create table if not exists public.rider_order_rejections(id uuid primary key default gen_random_uuid(),rider_id uuid not null,order_id uuid not null references public.orders(id) on delete cascade,created_at timestamptz not null default now(),unique(rider_id,order_id));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null,order_id uuid references public.orders(id) on delete cascade,type text not null default 'order',title text not null,body text not null,data jsonb not null default '{}'::jsonb,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.reviews(id uuid primary key default gen_random_uuid(),order_id uuid unique not null references public.orders(id) on delete cascade,customer_id uuid not null,restaurant_id uuid not null references public.restaurants(id) on delete cascade,rating int not null check(rating between 1 and 5),comment text,created_at timestamptz not null default now());

create or replace function public.current_profile_id() returns uuid language sql stable security definer set search_path=public as $$ select p.id from public.profiles p where p.firebase_uid=(auth.jwt()->>'sub') limit 1 $$;
revoke all on function public.current_profile_id() from public;
grant execute on function public.current_profile_id() to authenticated;

create or replace function public.ensure_firebase_profile(p_full_name text default 'Customer',p_phone text default '') returns table(profile_id uuid,role public.app_role) language plpgsql security definer set search_path=public as $$
declare v_uid text:=auth.jwt()->>'sub';v_email text:=auth.jwt()->>'email';v_name text:=nullif(trim(coalesce(p_full_name,'')),'');v_phone text:=nullif(trim(coalesce(p_phone,'')),'');v_profile public.profiles;
begin
 if v_uid is null or v_uid='' then raise exception 'Firebase user identity missing'; end if;
 select * into v_profile from public.profiles where firebase_uid=v_uid limit 1;
 if v_profile.id is null then
  if v_name is null then v_name:=split_part(coalesce(v_email,'Customer'),'@',1); end if;
  insert into public.profiles(id,firebase_uid,full_name,phone,role) values(gen_random_uuid(),v_uid,v_name,v_phone,'customer') returning * into v_profile;
 else
  update public.profiles set full_name=coalesce(v_name,full_name),phone=coalesce(v_phone,phone),updated_at=now() where id=v_profile.id returning * into v_profile;
 end if;
 return query select v_profile.id,v_profile.role;
end $$;
revoke all on function public.ensure_firebase_profile(text,text) from public;
grant execute on function public.ensure_firebase_profile(text,text) to authenticated;

alter table public.profiles enable row level security; alter table public.restaurant_applications enable row level security; alter table public.rider_applications enable row level security; alter table public.restaurants enable row level security; alter table public.menu_categories enable row level security; alter table public.menu_items enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.rider_locations enable row level security; alter table public.rider_order_rejections enable row level security; alter table public.notifications enable row level security; alter table public.reviews enable row level security;

do $$ begin
 drop policy if exists "public approved restaurants" on public.restaurants; drop policy if exists "public menus of approved restaurants" on public.menu_items; drop policy if exists "public menu categories of approved restaurants" on public.menu_categories; drop policy if exists "users read own profile" on public.profiles; drop policy if exists "users update own profile" on public.profiles; drop policy if exists "users create restaurant application" on public.restaurant_applications; drop policy if exists "users read own restaurant application" on public.restaurant_applications; drop policy if exists "users create rider application" on public.rider_applications; drop policy if exists "users read own rider application" on public.rider_applications; drop policy if exists "customers read own orders" on public.orders; drop policy if exists "customers create own orders" on public.orders; drop policy if exists "customers read own order items" on public.order_items; drop policy if exists "riders read own rejections" on public.rider_order_rejections; drop policy if exists "riders create own rejections" on public.rider_order_rejections; drop policy if exists "users read own notifications" on public.notifications; drop policy if exists "users update own notifications" on public.notifications; drop policy if exists "customers read own reviews" on public.reviews; drop policy if exists "customers create own reviews" on public.reviews;
end $$;
create policy "public approved restaurants" on public.restaurants for select using (is_approved=true);
create policy "public menus of approved restaurants" on public.menu_items for select using (exists(select 1 from public.restaurants r where r.id=restaurant_id and r.is_approved=true));
create policy "public menu categories of approved restaurants" on public.menu_categories for select using (exists(select 1 from public.restaurants r where r.id=restaurant_id and r.is_approved=true));
create policy "firebase users read own profile" on public.profiles for select using (public.current_profile_id()=id);
create policy "firebase users update own profile" on public.profiles for update using (public.current_profile_id()=id) with check (public.current_profile_id()=id);
create policy "firebase users create restaurant application" on public.restaurant_applications for insert with check (public.current_profile_id()=applicant_id); create policy "firebase users read restaurant application" on public.restaurant_applications for select using (public.current_profile_id()=applicant_id);
create policy "firebase users create rider application" on public.rider_applications for insert with check (public.current_profile_id()=applicant_id); create policy "firebase users read rider application" on public.rider_applications for select using (public.current_profile_id()=applicant_id);
create policy "firebase users read own orders" on public.orders for select using (public.current_profile_id()=customer_id or public.current_profile_id()=rider_id or exists(select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=public.current_profile_id()));
create policy "firebase users read own order items" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=public.current_profile_id() or o.rider_id=public.current_profile_id() or exists(select 1 from public.restaurants r where r.id=o.restaurant_id and r.owner_id=public.current_profile_id()))));
create policy "firebase riders read own rejections" on public.rider_order_rejections for select using (public.current_profile_id()=rider_id); create policy "firebase riders create own rejections" on public.rider_order_rejections for insert with check (public.current_profile_id()=rider_id);
create policy "firebase users read own notifications" on public.notifications for select using (public.current_profile_id()=user_id); create policy "firebase users update own notifications" on public.notifications for update using (public.current_profile_id()=user_id) with check (public.current_profile_id()=user_id);
create policy "firebase users read own reviews" on public.reviews for select using (public.current_profile_id()=customer_id); create policy "firebase users create own reviews" on public.reviews for insert with check (public.current_profile_id()=customer_id);

do $$ begin alter publication supabase_realtime add table public.orders; exception when duplicate_object then null; end $$; do $$ begin alter publication supabase_realtime add table public.notifications; exception when duplicate_object then null; end $$; do $$ begin alter publication supabase_realtime add table public.rider_locations; exception when duplicate_object then null; end $$;
create index if not exists idx_profiles_firebase_uid on public.profiles(firebase_uid) where firebase_uid is not null; create index if not exists idx_orders_customer_created on public.orders(customer_id,created_at desc); create index if not exists idx_orders_restaurant_status on public.orders(restaurant_id,status,created_at desc); create index if not exists idx_orders_rider_status on public.orders(rider_id,status,created_at desc); create index if not exists idx_rider_locations_online_updated on public.rider_locations(is_online,updated_at desc); create index if not exists idx_notifications_user_created on public.notifications(user_id,created_at desc); create index if not exists idx_rejections_rider_order on public.rider_order_rejections(rider_id,order_id);
-- Production service-area enforcement is also applied in Edge Functions. BFD_BARMER_RADIUS_KM defaults to 35 km around Barmer city and can be configured server-side.
-- Never trust a client-provided role, approval flag, rider assignment, price or admin decision.
