import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
 const auth=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:req.headers.get('Authorization')??''}}});
 const {data:{user}}=await auth.auth.getUser(); if(!user)return json({error:'Authentication required'},401);
 const {data:profile}=await admin.from('profiles').select('role').eq('id',user.id).maybeSingle(); if(profile?.role!=='admin')return json({error:'Admin only'},403);
 const body=await req.json().catch(()=>null); const lat=Number(body?.lat),lng=Number(body?.lng);
 if(!body?.order_id||!Number.isFinite(lat)||!Number.isFinite(lng))return json({error:'order_id, lat and lng are required'},400);
 const {data:order}=await admin.from('orders').select('id,status,rider_id,restaurant_id').eq('id',body.order_id).maybeSingle();
 if(!order)return json({error:'Order not found'},404);
 if(order.status!=='ready_for_pickup'||order.rider_id)return json({error:'Order is not awaiting rider assignment'},409);
 const cutoff=new Date(Date.now()-2*60*1000).toISOString();
 const {data:riders,error}=await admin.from('rider_locations').select('rider_id,latitude,longitude,updated_at').eq('is_online',true).gte('updated_at',cutoff).limit(200);
 if(error)return json({error:error.message},500);
 const ids=[...new Set((riders??[]).map((r:any)=>r.rider_id))]; if(!ids.length)return json({error:'No nearby online rider available'},409);
 const {data:approved}=await admin.from('rider_applications').select('applicant_id').eq('status','approved').in('applicant_id',ids);
 const approvedIds=new Set((approved??[]).map((r:any)=>r.applicant_id));
 const distance=(a:number,b:number,c:number,d:number)=>{const R=6371,rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,q=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q));};
 const candidates=(riders??[]).filter((r:any)=>approvedIds.has(r.rider_id)).map((r:any)=>({...r,km:distance(lat,lng,Number(r.latitude),Number(r.longitude))})).filter((r:any)=>r.km<=15).sort((a:any,b:any)=>a.km-b.km);
 const selected=candidates[0]; if(!selected)return json({error:'No nearby approved online rider available'},409);
 const {data:updated,error:updateError}=await admin.from('orders').update({rider_id:selected.rider_id,status:'rider_assigned'}).eq('id',body.order_id).eq('status','ready_for_pickup').is('rider_id',null).select('id,rider_id,status').maybeSingle();
 if(updateError)return json({error:updateError.message},500); if(!updated)return json({error:'Order was assigned by another dispatcher; refresh and retry'},409);
 const {error:notifyError}=await admin.from('notifications').insert({user_id:selected.rider_id,order_id:body.order_id,title:'नया delivery order',body:`Order ${body.order_id} आपके पास है`});
 if(notifyError)return json({error:notifyError.message},500);
 return json({ok:true,order_id:body.order_id,rider_id:selected.rider_id,distance_km:Number(selected.km.toFixed(2))});
});
