const demoRestaurants=Array.isArray(window.BFD_DEMO_RESTAURANTS)?window.BFD_DEMO_RESTAURANTS:[];
const state={page:'home',restaurant:null,cart:[],orders:JSON.parse(localStorage.getItem('bfd_orders')||'[]'),role:'customer',toast:''};
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem('bfd_orders',JSON.stringify(state.orders));
function toast(t){state.toast=t;render();setTimeout(()=>{state.toast='';render()},2200)}
function shell(content){return `<div class="app"><header class="top"><div class="brand"><div><div class="logo">🍽️ Barmer Food Delivery</div><div class="location">📍 Barmer, Rajasthan • केवल Barmer में</div></div><button class="btn secondary" onclick="openProfile()">👤</button></div></header><main class="page">${content}</main><nav class="bottom"><div class="nav"><button class="${state.page==='home'?'active':''}" onclick="go('home')">⌂<br><small>Home</small></button><button class="${state.page==='search'?'active':''}" onclick="go('search')">⌕<br><small>Search</small></button><button class="${state.page==='orders'?'active':''}" onclick="go('orders')">🧾<br><small>Orders</small></button><button class="${state.page==='profile'?'active':''}" onclick="openProfile()">☻<br><small>Profile</small></button></div></nav>${state.toast?`<div class="toast">${state.toast}</div>`:''}</div>`}
function home(){return shell(`<div class="container"><section class="hero"><h1>खाना चाहिए? Barmer में मंगाइए! 😋</h1><p>आपके शहर के verified restaurants से ताज़ा खाना, आपके दरवाज़े तक।</p><div class="search" onclick="go('search')">🔎  होटल, खाना या cuisine खोजें...</div></section><div class="section-title"><h2>आज के लोकप्रिय होटल</h2><span class="muted">Barmer</span></div><div class="grid">${demoRestaurants.map(r=>restaurantCard(r)).join('')}</div><div class="section-title"><h2>कैसे काम करता है?</h2></div><div class="panel"><div class="row"><span>1️⃣ होटल चुनें</span><span>→</span><span>2️⃣ Order करें</span><span>→</span><span>3️⃣ Rider ट्रैक करें</span></div></div></div>`)}
function restaurantCard(r){return `<article class="card"><div class="food-img">${r.emoji}</div><div class="card-body"><h3>${r.name}</h3><div class="muted" style="font-size:12px">${r.cuisine}</div><p><span class="pill">★ ${r.rating}</span> <span class="muted"> ${r.time}</span></p><div class="row"><span class="muted">Delivery ₹${r.fee}</span><button class="btn primary" onclick="openRestaurant(${r.id})">Menu</button></div></div></article>`}
function openRestaurant(id){state.restaurant=demoRestaurants.find(x=>x.id===id);state.page='restaurant';render()}
function restaurant(){const r=state.restaurant;return shell(`<div class="container"><button class="back" onclick="go('home')">← वापस</button><section class="hero" style="margin-top:14px"><h1>${r.emoji} ${r.name}</h1><p>★ ${r.rating} • ${r.cuisine} • ${r.time}</p></section><div class="section-title"><h2>Menu</h2><span class="muted">₹${r.fee} delivery</span></div><div class="panel">${r.items.map((i,n)=>`<div class="menu-item"><div class="thumb">${i[2]}</div><div class="grow"><h3>${i[0]}</h3><p class="muted">Freshly prepared • Veg</p><b>₹${i[1]}</b></div><button class="add" onclick="add(${n})">+ Add</button></div>`).join('')}</div>${state.cart.length?`<div class="panel"><div class="row"><b>🛒 ${state.cart.length} items</b><b>₹${state.cart.reduce((a,x)=>a+x.price,0)}</b><button class="btn primary" onclick="checkout()">Cart →</button></div></div>`:''}</div>`)}
function add(n){const i=state.restaurant.items[n];state.cart.push({name:i[0],price:i[1]});toast(`${i[0]} cart में जुड़ गया`)}
function checkout(){state.page='checkout';render()}
function checkoutPage(){const total=state.cart.reduce((a,x)=>a+x.price,0),fee=state.restaurant.fee;return shell(`<div class="container"><button class="back" onclick="openRestaurant(${state.restaurant.id})">← Menu</button><h2>Checkout</h2><div class="panel"><h3>Delivery Address</h3><p>📍 अपना Barmer address चुनें</p><button class="btn secondary">+ Add address</button></div><div class="panel"><h3>Payment</h3><label>◉ Cash on Delivery</label><br><label>○ Online payment (Test)</label></div><div class="panel"><div class="row"><span>Items</span><b>₹${total}</b></div><div class="row"><span>Delivery</span><b>₹${fee}</b></div><hr><div class="row"><b>Total</b><b>₹${total+fee}</b></div><button class="btn primary" style="width:100%;margin-top:14px" onclick="placeOrder()">Place Order • ₹${total+fee}</button></div></div>`)}
function placeOrder(){const r=state.restaurant,total=state.cart.reduce((a,x)=>a+x.price,0)+r.fee;const o={id:'BFD'+Date.now().toString().slice(-6),restaurant:r.name,total,status:'restaurant_notified',created:new Date().toLocaleString('hi-IN'),rider:null};state.orders.unshift(o);state.cart=[];save();state.page='orders';toast('Order होटल को भेज दिया गया 🔔')}
function orders(){return shell(`<div class="container"><div class="section-title"><h2>मेरे Orders</h2></div>${state.orders.length?state.orders.map(o=>`<div class="panel"><div class="row"><div><b>#${o.id}</b><p style="margin:5px 0">${o.restaurant}</p></div><span class="status">${label(o.status)}</span></div><p class="muted">${o.created} • ₹${o.total}</p><button class="btn primary" onclick="track('${o.id}')">Live Track →</button></div>`).join(''):`<div class="empty">🧾<h3>अभी कोई order नहीं</h3><p>अपने पसंदीदा होटल से पहला order करें।</p><button class="btn primary" onclick="go('home')">खाना देखें</button></div>`}</div>`)}
function label(s){return {restaurant_notified:'Hotel को notification',accepted:'Hotel ने accept किया',preparing:'खाना तैयार हो रहा है',ready_for_pickup:'Pickup के लिए तैयार',rider_assigned:'Rider मिल गया',picked_up:'Rider ने खाना ले लिया',on_the_way:'आपके पास आ रहा है',delivered:'Delivered',cancelled:'Cancelled'}[s]||s}
function track(id){const o=state.orders.find(x=>x.id===id);state.page='track';state.track=o;render()}
function tracking(){const o=state.track;return shell(`<div class="container"><button class="back" onclick="go('orders')">← Orders</button><h2>Live Order Tracking</h2><div class="panel"><div class="row"><div><b>#${o.id}</b><p>${o.restaurant}</p></div><span class="status">${label(o.status)}</span></div></div><div class="map"><div class="road"></div><div class="route"></div><div class="marker m1">🏨</div><div class="marker m2">📍</div><div class="marker m3">🛵</div></div><div class="panel"><h3>Delivery journey</h3><p>✅ Order placed</p><p>🔔 Restaurant notified</p><p>${['accepted','preparing','ready_for_pickup','rider_assigned','picked_up','on_the_way','delivered'].includes(o.status)?'✅':'○'} Hotel accepted & preparing</p><p>${['rider_assigned','picked_up','on_the_way','delivered'].includes(o.status)?'✅':'○'} Rider assigned</p><p>${['picked_up','on_the_way','delivered'].includes(o.status)?'✅':'○'} Pickup completed</p><p>${o.status==='delivered'?'✅':'○'} Delivered to you</p></div><button class="btn primary" style="width:100%" onclick="simulateOrder('${o.id}')">Demo: Advance status</button></div>`)}
function simulateOrder(id){const o=state.orders.find(x=>x.id===id), flow=['restaurant_notified','accepted','preparing','ready_for_pickup','rider_assigned','picked_up','on_the_way','delivered'],n=flow.indexOf(o.status);if(n<flow.length-1){o.status=flow[n+1];save();toast('Order status updated')}else toast('Order delivered 🎉');render()}
function search(){return shell(`<div class="container"><h2>Search</h2><input class="search" style="width:100%;border:1px solid #ddd" placeholder="Hotel या food खोजें..." oninput="filterRestaurants(this.value)"><div id="results" class="grid" style="margin-top:16px">${demoRestaurants.map(r=>restaurantCard(r)).join('')}</div></div>`)}
function filterRestaurants(q){const arr=demoRestaurants.filter(r=>(r.name+' '+r.cuisine+' '+r.items.map(x=>x[0]).join(' ')).toLowerCase().includes(q.toLowerCase()));$('#results').innerHTML=arr.map(restaurantCard).join('')||'<div class="empty">कोई restaurant नहीं मिला</div>'}
function profile(){return shell(`<div class="container"><h2>Profile & Settings</h2><div class="panel"><h3>👤 Customer</h3><p class="muted">Login / account management यहाँ उपलब्ध रहेगा।</p><button class="btn secondary">Login / Sign up</button></div><div class="section-title"><h3>Career / Partner with us</h3></div><div class="panel"><p>Barmer में food delivery network का हिस्सा बनें।</p><div class="row"><button class="btn primary" onclick="partner('restaurant')">🏨 Restaurant / Hotel Partner</button><button class="btn secondary" onclick="partner('rider')">🛵 Delivery Rider</button></div></div><div class="panel"><h3>Help & Support</h3><p>📞 Customer support • Terms • Privacy</p></div></div>`)}
function partner(type){state.page='partner';state.partnerType=type;render()}
function partnerPage(){const rider=state.partnerType==='rider';return shell(`<div class="container"><button class="back" onclick="openProfile()">← Profile</button><h2>${rider?'🛵 Rider Registration':'🏨 Restaurant / Hotel Partner'}</h2><p class="muted">Verification के बाद ही account activate होगा और public listing/job access मिलेगा।</p><form class="panel form" onsubmit="submitPartner(event)"><input required placeholder="पूरा नाम / Owner name"><input required placeholder="Mobile number"><input required placeholder="${rider?'पूरा पता':'Hotel / Restaurant name'}"><input required placeholder="Barmer area / address"><input placeholder="${rider?'Vehicle number':'GST / FSSAI / registration number'}"><input type="file" accept="image/*,.pdf" multiple required><textarea placeholder="Additional information"></textarea><button class="btn primary">Verification request भेजें</button></form></div>`)}
function submitPartner(e){e.preventDefault();toast('Verification request admin को भेज दी गई ✓');openProfile()}
function admin(){return `<div class="container"><div class="section-title"><div><div class="logo">🛡️ Barmer Food Delivery Admin</div><div class="muted">Secure administration</div></div><button class="btn secondary" onclick="go('home')">Exit</button></div><div class="stats"><div class="stat">Orders<b>${state.orders.length}</b></div><div class="stat">Restaurants<b>4</b></div><div class="stat">Riders<b>12</b></div><div class="stat">Pending<b>3</b></div></div><div class="panel"><h3>Verification Requests</h3><div class="row"><span>🏨 Shree Hotel • Barmer</span><span class="pill">Pending</span><button class="btn primary" onclick="toast('Restaurant approved')">Approve</button></div><hr><div class="row"><span>🛵 Rider • KYC submitted</span><span class="pill">Pending</span><button class="btn primary" onclick="toast('Rider approved')">Approve</button></div></div><div class="panel"><h3>Operations</h3><p>Live orders • Dispatch • Service area • Coupons • Commission • Payouts • Support • Audit logs</p></div></div>`}
function adminLogin(){const p=prompt('Admin password दर्ज करें');if(p){state.page='admin';render()}}
function go(p){state.page=p;render()} function openProfile(){state.page='profile';render()}
function render(){let c=state.page==='home'?home():state.page==='search'?search():state.page==='orders'?orders():state.page==='restaurant'?restaurant():state.page==='checkout'?checkoutPage():state.page==='track'?tracking():state.page==='profile'?profile():state.page==='partner'?partnerPage():state.page==='admin'?admin():home();$('#app').innerHTML=c}
window.go=go;window.openRestaurant=openRestaurant;window.add=add;window.checkout=checkout;window.placeOrder=placeOrder;window.track=track;window.simulateOrder=simulateOrder;window.filterRestaurants=filterRestaurants;window.openProfile=openProfile;window.partner=partner;window.submitPartner=submitPartner;window.adminLogin=adminLogin;
render();
