/* Barmer Food Delivery — actual private KYC upload portal. */
(function(){'use strict';const api=window.BFD_SUPABASE;if(!api?.ready)return;const root=()=>document.getElementById('app');const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const toast=t=>{const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2600)};const MAX=5*1024*1024,OK=new Set(['image/jpeg','image/png','application/pdf']);
function frame(body){return `<div class="app"><header class="top"><div class="brand"><div><div class="logo">🔐 KYC Verification</div><div class="location">Barmer Food Delivery • Secure Documents</div></div><button class="btn secondary" onclick="bfdPartnerHome?.()">⌂</button></div></header><main class="page">${body}</main></div>`}
async function user(){const u=await api.user();if(!u){toast('पहले login करें');window.bfdLiveAuth?.();return null}return u}
async function listDocs(uid){const r=await api.client.from('kyc_documents').select('id,document_type,application_type,application_id,original_name,mime_type,size_bytes,status,admin_note,reviewed_at,created_at').eq('user_id',uid).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
function status(s){return `<span class="status">${esc(s)}</span>`}
async function render(){const u=await user();if(!u)return;try{const docs=await listDocs(u.id);root().innerHTML=frame(`<div class="container"><button class="back" onclick="bfdPartnerHome?.()">← Partner Centre</button><h2>📄 KYC Documents</h2><div class="panel"><p>केवल JPG, PNG या PDF • अधिकतम 5 MB प्रति फाइल • दस्तावेज private storage में रखे जाते हैं।</p><label class="field"><span>Application type</span><select id="kyc-app-type" class="search"><option value="rider">Delivery Rider</option><option value="restaurant">Restaurant / Hotel</option></select></label><label class="field"><span>Application ID (optional)</span><input id="kyc-app-id" class="search" placeholder="Application UUID"></label><label class="field"><span>Document type</span><select id="kyc-type" class="search"><option value="aadhaar">Aadhaar / ID</option><option value="pan">PAN</option><option value="driving_license">Driving Licence</option><option value="vehicle_rc">Vehicle RC</option><option value="bank_proof">Bank proof</option><option value="profile_photo">Profile photo</option><option value="other">Other</option></select></label><label class="field"><span>File</span><input id="kyc-file" class="search" type="file" accept="image/jpeg,image/png,application/pdf"></label><button id="kyc-upload" class="btn primary" style="width:100%" onclick="bfdUploadKyc()">Secure Upload करें</button><p id="kyc-progress" class="muted"></p></div><h3>Submitted documents</h3>${docs.map(d=>`<div class="panel"><div class="row"><b>${esc(d.document_type)}</b>${status(d.status)}</div><p class="muted">${esc(d.original_name||'Private document')} • ${d.size_bytes?Math.ceil(d.size_bytes/1024)+' KB':''}</p>${d.admin_note?`<p>Admin note: ${esc(d.admin_note)}</p>`:''}${d.status!=='rejected'?`<button class="btn secondary" onclick="bfdViewKyc('${d.id}')">Secure preview</button>`:''}</div>`).join('')||'<div class="empty">अभी कोई document submit नहीं हुआ।</div>'}</div>`)}catch(e){toast(e.message||'KYC load failed')}}
async function upload(){const u=await user();if(!u)return;const f=document.getElementById('kyc-file')?.files?.[0];const type=document.getElementById('kyc-type')?.value;if(!f)return toast('पहले file चुनें');if(!OK.has(f.type))return toast('सिर्फ JPG, PNG या PDF allowed है');if(f.size>MAX)return toast('File 5 MB से बड़ी है');const btn=document.getElementById('kyc-upload'),p=document.getElementById('kyc-progress');btn.disabled=true;p.textContent='Uploading securely…';try{const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100)||'document';const path=`${u.id}/${crypto.randomUUID()}-${safe}`;const up=await api.client.storage.from('kyc-documents').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type});if(up.error)throw up.error;const body={document_type:type,storage_path:path,original_name:f.name.slice(0,180),application_type:document.getElementById('kyc-app-type').value,application_id:document.getElementById('kyc-app-id').value.trim()||null};const r=await api.client.functions.invoke('kyc-submit',{body});if(r.error){await api.client.storage.from('kyc-documents').remove([path]);throw r.error}toast('KYC document सुरक्षित रूप से submit हो गया');await render()}catch(e){p.textContent='';toast(e?.message||'Upload failed')}finally{btn.disabled=false}}
async function view(id){try{const r=await api.client.functions.invoke('kyc-signed-url',{body:{document_id:id}});if(r.error)throw r.error;if(r.data?.url)window.open(r.data.url,'_blank','noopener');else toast('Preview unavailable')}catch(e){toast(e.message||'Preview failed')}}
window.bfdKycPortal=render;window.bfdUploadKyc=upload;window.bfdViewKyc=view;})();
