package com.malaramofficial.barmerfooddelivery;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.location.*;import android.net.Uri;import android.os.Bundle;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import org.json.*;import java.util.*;

/** Native Android customer UI. No WebView/browser-hosted screens. */
public class MainActivity extends Activity{
 private static final int LOC=1001; private NativeApi api; private LinearLayout root,content; private final ArrayList<JSONObject> cart=new ArrayList<>(); private String restaurantId="",restaurantName=""; private double lat,lng;
 private final int ORANGE=Color.rgb(245,124,0),DARK=Color.rgb(38,38,38),MUTED=Color.rgb(105,105,105),BG=Color.rgb(248,248,248);
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);api=new NativeApi(this);showHome();}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private TextView text(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(DARK);v.setPadding(dp(4),dp(4),dp(4),dp(4));return v;}
 private TextView title(String s){TextView v=text(s,24);v.setTypeface(null,1);return v;}
 private GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp((int)r));return g;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setMinHeight(dp(50));b.setPadding(dp(12),0,dp(12),0);b.setBackground(bg(ORANGE,12));return b;}
 private Button lightBtn(String s){Button b=btn(s);b.setTextColor(DARK);b.setBackground(bg(Color.WHITE,12));b.setElevation(dp(1));return b;}
 private void base(String name){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(16),dp(10),dp(16),dp(16));
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView h=title(name);top.addView(h,new LinearLayout.LayoutParams(0,dp(58),1));Button p=lightBtn("Profile");p.setOnClickListener(v->showProfile());top.addView(p,new LinearLayout.LayoutParams(dp(108),dp(48)));root.addView(top);
  ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,dp(6),0,dp(20));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
 }
 private void add(View v){content.addView(v,new LinearLayout.LayoutParams(-1,-2));} private void gap(int n){Space s=new Space(this);add(s);s.getLayoutParams().height=dp(n);}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(bg(Color.WHITE,16));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));c.setLayoutParams(p);return c;}
 private void showHome(){base("Barmer Food Delivery");TextView hero=text("🍽️  बारमेर में स्वादिष्ट खाना\nआपके दरवाज़े तक",22);hero.setTypeface(null,1);add(hero);TextView sub=text("Approved restaurants • Fast delivery • COD",14);sub.setTextColor(MUTED);add(sub);gap(8);Button loc=btn("📍  Delivery location सेट करें");loc.setOnClickListener(v->requestLocation());add(loc);gap(8);add(title("Restaurants & Hotels"));loadRestaurants();gap(6);Button o=lightBtn("📦  My Orders");o.setOnClickListener(v->showOrders());add(o);Button n=lightBtn("🔔  Notifications");n.setOnClickListener(v->showNotifications());add(n);Button p=lightBtn("🤝  Careers / Partner with us");p.setOnClickListener(v->showPartner());add(p);}
 private void loadRestaurants(){if(!api.configured()){TextView e=text("Backend configuration अभी बाकी है.\nGitHub Actions में Supabase URL और anon key secrets देने के बाद live restaurants दिखेंगे.",15);e.setTextColor(MUTED);add(e);return;}api.restaurants(new NativeApi.Callback(){public void ok(JSONObject r){runOnUiThread(()->{try{JSONArray a=r.optJSONArray("data");if(a==null||a.length()==0){add(text("अभी कोई approved restaurant उपलब्ध नहीं है.",15));return;}for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);LinearLayout c=card();TextView h=text("🍛  "+x.optString("name"),18);h.setTypeface(null,1);c.addView(h);TextView d=text(x.optString("cuisine","Food")+"  •  "+x.optString("area","Barmer")+"\nDelivery ₹"+x.optDouble("delivery_fee",0)+(x.optBoolean("is_open")?"  •  Open":"  •  Closed"),14);d.setTextColor(MUTED);c.addView(d);Button m=btn(x.optBoolean("is_open")?"View Menu":"Closed");m.setEnabled(x.optBoolean("is_open"));m.setOnClickListener(v->showMenu(x));c.addView(m);content.addView(c);} }catch(Exception e){add(text("Restaurant data error: "+e.getMessage(),14));}});}public void error(String m){runOnUiThread(()->add(text("Restaurants: "+m,14)));}});}
 private void showMenu(JSONObject r){restaurantId=r.optString("id");restaurantName=r.optString("name");cart.clear();base(restaurantName);add(text("🍴  Menu • "+r.optString("cuisine","Food"),18));api.menu(restaurantId,new NativeApi.Callback(){public void ok(JSONObject z){runOnUiThread(()->{try{JSONArray a=z.optJSONArray("data");if(a==null||a.length()==0){add(text("Menu उपलब्ध नहीं है.",15));return;}for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);LinearLayout c=card();LinearLayout row=new LinearLayout(MainActivity.this);row.setGravity(Gravity.CENTER_VERTICAL);TextView q=text(x.optString("name")+"\n₹"+x.optDouble("price",0)+"\n"+x.optString("description",""),15);row.addView(q,new LinearLayout.LayoutParams(0,-2,1));Button ad=btn("+ Add");ad.setOnClickListener(v->{cart.add(x);Toast.makeText(MainActivity.this,"Cart में जोड़ा",Toast.LENGTH_SHORT).show();});row.addView(ad,new LinearLayout.LayoutParams(dp(90),dp(48)));c.addView(row);content.addView(c);}Button c=btn("🛒  Cart ("+cart.size()+")");c.setOnClickListener(v->showCart());add(c);}catch(Exception e){add(text(e.getMessage(),14));}});}public void error(String m){runOnUiThread(()->add(text("Menu: "+m,14)));}});}
 private void showCart(){base("Your Cart");if(cart.isEmpty()){add(text("🛒  Cart खाली है",18));return;}double total=0;for(JSONObject x:cart){double p=x.optDouble("price",0);total+=p;LinearLayout c=card();c.addView(text(x.optString("name")+"  —  ₹"+p,16));add(c);}TextView sum=text("Subtotal   ₹"+total,19);sum.setTypeface(null,1);add(sum);gap(8);Button c=btn("Proceed to Checkout • COD");c.setOnClickListener(v->showCheckout());add(c);}
 private void showCheckout(){base("Checkout");add(text("Restaurant: "+restaurantName,17));EditText address=new EditText(this);address.setHint("पूरा delivery address");address.setTextSize(16);address.setMinHeight(dp(58));address.setSingleLine(false);address.setBackground(bg(Color.WHITE,12));address.setPadding(dp(14),dp(8),dp(14),dp(8));add(address);gap(6);Button l=lightBtn("📍  Use current GPS location");l.setOnClickListener(v->requestLocation());add(l);gap(6);add(text("💵  Payment: Cash on Delivery",16));gap(8);Button place=btn("Place Order");place.setOnClickListener(v->{if(!api.signedIn()){showLogin();return;}if(address.getText().toString().trim().length()<5){address.setError("पूरा address लिखें");return;}if(lat==0||lng==0){Toast.makeText(this,"पहले GPS location सेट करें",Toast.LENGTH_LONG).show();return;}try{JSONArray items=new JSONArray();for(JSONObject x:cart){JSONObject q=new JSONObject();q.put("menu_item_id",x.optString("id"));q.put("quantity",1);items.put(q);}place.setEnabled(false);api.createOrder(restaurantId,address.getText().toString().trim(),lat,lng,"cod",items,new NativeApi.Callback(){public void ok(JSONObject d){runOnUiThread(()->{cart.clear();Toast.makeText(MainActivity.this,"Order सफलतापूर्वक भेज दिया गया",Toast.LENGTH_LONG).show();showOrders();});}public void error(String m){runOnUiThread(()->{place.setEnabled(true);Toast.makeText(MainActivity.this,m,Toast.LENGTH_LONG).show();});}});}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});add(place);}
 private void showOrders(){base("My Orders");if(!api.signedIn()){add(text("Orders देखने के लिए login करें.",17));Button b=btn("Login");b.setOnClickListener(v->showLogin());add(b);return;}api.orders(new NativeApi.Callback(){public void ok(JSONObject d){runOnUiThread(()->{try{JSONArray a=d.optJSONArray("data");if(a==null||a.length()==0){add(text("📦  No orders yet.",17));return;}for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);LinearLayout c=card();String id=o.optString("id");c.addView(text("Order #"+id.substring(0,Math.min(8,id.length())),17));c.addView(text("Status: "+o.optString("status")+"\nTotal: ₹"+o.optDouble("total",0)+"\n"+o.optString("delivery_address"),15));Button tr=btn("📍  Track / Navigate");tr.setOnClickListener(v->showTracking(o));c.addView(tr);content.addView(c);}}catch(Exception e){add(text(e.getMessage(),14));}});}public void error(String m){runOnUiThread(()->add(text("Orders: "+m,14)));}});}
 private void showTracking(JSONObject o){base("Live Order Tracking");TextView s=text("Order status\n"+o.optString("status"),21);s.setTypeface(null,1);add(s);double a=o.optDouble("delivery_latitude",0),b=o.optDouble("delivery_longitude",0);if(a!=0&&b!=0){add(text("📍 Delivery pin: "+a+", "+b,14));Button nav=btn("🧭  Open navigation");nav.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("google.navigation:q="+a+","+b));try{startActivity(i);}catch(Exception e){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("geo:"+a+","+b+"?q="+a+","+b)));}});add(nav);}add(text("Realtime order data is connected to the Supabase backend. Native in-app map/driver tracking is the next production integration and requires the map provider key.",14));}
 private void showNotifications(){base("Notifications");if(!api.signedIn()){add(text("Login required.",16));return;}api.notifications(new NativeApi.Callback(){public void ok(JSONObject d){runOnUiThread(()->{JSONArray a=d.optJSONArray("data");if(a==null||a.length()==0){add(text("🔔  No notifications.",16));return;}for(int i=0;i<a.length();i++){JSONObject n=a.optJSONObject(i);LinearLayout c=card();c.addView(text("🔔  "+n.optString("title"),16));c.addView(text(n.optString("body"),14));content.addView(c);}});}public void error(String m){runOnUiThread(()->add(text(m,14)));}});}
 private void showProfile(){base("Profile");if(!api.signedIn()){add(text("Customer account",18));Button b=btn("Login / Sign up");b.setOnClickListener(v->showLogin());add(b);}else{api.profile(new NativeApi.Callback(){public void ok(JSONObject d){runOnUiThread(()->{JSONArray a=d.optJSONArray("data");JSONObject p=a==null?null:a.optJSONObject(0);add(text("👤  "+(p==null?"Customer":p.optString("full_name","Customer"))+"\n📱  "+(p==null?"":p.optString("phone"))+"\nRole: "+(p==null?"customer":p.optString("role")),17));Button s=btn("Sign out");s.setOnClickListener(v->{api.signOut();showHome();});add(s);});}public void error(String m){runOnUiThread(()->add(text(m,14)));}});}Button p=lightBtn("🤝  Careers / Partner with us");p.setOnClickListener(v->showPartner());add(p);}
 private void showLogin(){base("Login / Sign up");add(text("Welcome back 👋",18));EditText email=input("Email");EditText pass=input("Password");pass.setInputType(129);EditText name=input("नाम (signup के लिए)");EditText phone=input("मोबाइल (signup के लिए)");Button login=btn("Login");login.setOnClickListener(v->{hideKeyboard();api.signIn(email.getText().toString().trim(),pass.getText().toString(),result("Login successful"));});add(login);Button signup=lightBtn("Create account");signup.setOnClickListener(v->{hideKeyboard();api.signUp(email.getText().toString().trim(),pass.getText().toString(),name.getText().toString().trim(),phone.getText().toString().trim(),result("Account created"));});add(signup);}
 private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setMinHeight(dp(58));e.setPadding(dp(14),0,dp(14),0);e.setBackground(bg(Color.WHITE,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(5),0,dp(5));content.addView(e,p);return e;}
 private void hideKeyboard(){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(root.getWindowToken(),0);}
 private NativeApi.Callback result(String ok){return new NativeApi.Callback(){public void ok(JSONObject d){runOnUiThread(()->{Toast.makeText(MainActivity.this,ok,Toast.LENGTH_SHORT).show();showHome();});}public void error(String m){runOnUiThread(()->Toast.makeText(MainActivity.this,m,Toast.LENGTH_LONG).show());}};}
 private void showPartner(){base("Partner with us");add(text("Restaurant/Hotel या Delivery Rider के रूप में जुड़ें.",17));gap(8);Button r=btn("🏨  Restaurant / Hotel Partner");r.setOnClickListener(v->restaurantForm());add(r);Button d=lightBtn("🛵  Delivery Rider");d.setOnClickListener(v->riderForm());add(d);}
 private EditText field(String hint){return input(hint);}
 private void restaurantForm(){if(!api.signedIn()){showLogin();return;}base("Restaurant / Hotel");add(text("Partner application",18));EditText name=field("Restaurant/Hotel name *"),owner=field("Owner name *"),phone=field("Phone *"),addr=field("Address *"),area=field("Barmer area *"),reg=field("Registration/GST no. (optional)");Button s=btn("Submit Application");s.setOnClickListener(v->{JSONObject b=new JSONObject();try{b.put("applicant_id",api.userId());b.put("restaurant_name",name.getText().toString());b.put("owner_name",owner.getText().toString());b.put("phone",phone.getText().toString());b.put("address",addr.getText().toString());b.put("barmer_area",area.getText().toString());b.put("registration_no",reg.getText().toString());api.applyRestaurant(b,result("Application submitted"));}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});add(s);}
 private void riderForm(){if(!api.signedIn()){showLogin();return;}base("Delivery Rider");add(text("Rider application",18));EditText name=field("Full name *"),phone=field("Phone *"),addr=field("Address *"),vehicle=field("Vehicle number"),lic=field("Driving licence number"),em=field("Emergency contact");Button s=btn("Submit Application");s.setOnClickListener(v->{JSONObject b=new JSONObject();try{b.put("applicant_id",api.userId());b.put("full_name",name.getText().toString());b.put("phone",phone.getText().toString());b.put("address",addr.getText().toString());b.put("vehicle_no",vehicle.getText().toString());b.put("licence_no",lic.getText().toString());b.put("emergency_contact",em.getText().toString());api.applyRider(b,result("Application submitted"));}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});add(s);}
 private void requestLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOC);return;}LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);try{Location x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(x==null)x=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(x!=null){lat=x.getLatitude();lng=x.getLongitude();Toast.makeText(this,"Location set",Toast.LENGTH_SHORT).show();}else Toast.makeText(this,"GPS location अभी उपलब्ध नहीं है",Toast.LENGTH_LONG).show();}catch(SecurityException e){Toast.makeText(this,"Location permission required",Toast.LENGTH_LONG).show();}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==LOC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)requestLocation();}
}
