import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}; const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); if(req.method!=='POST')return json({error:'Method not allowed'},405);
 const service=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!); const auth=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:req.headers.get('Authorization')??''}}}); const {data:{user}}=await auth.auth.getUser(); if(!user)return json({error:'Authentication required'},401);
 const {data:p}=await service.from('profiles').select('role').eq('id',user.id).maybeSingle(); if(p?.role!=='admin')return json({error:'Admin only'},403);
 const body=await req.json().catch(()=>null); const type=body?.type, id=body?.id, action=body?.action; if(!id||!['restaurant','rider','order'].includes(type)||!['approve','reject','suspend','open','close','cancel'].includes(action))return json({error:'Invalid admin action'},400);
 if(type==='restaurant'){const allowed=['approve','reject','suspend','open','close']; if(!allowed.includes(action))return json({error:'Invalid restaurant action'},400); const patch:any={}; if(action==='approve')patch.is_approved=true; if(action==='reject'||action==='suspend')patch.is_approved=false; if(action==='open')patch.is_open=true; if(action==='close')patch.is_open=false; const {data,error}=await service.from('restaurants').update(patch).eq('id',id).select('id,name,is_approved,is_open').maybeSingle(); if(error||!data)return json({error:error?.message??'Restaurant not found'},404); return json({ok:true,type,action,data});}
 if(type==='rider'){if(action==='approve'||action==='reject'||action==='suspend'){const status=action==='approve'?'approved':action; const {data,error}=await service.from('rider_applications').update({status,reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq('id',id).eq('status','pending').select('id,applicant_id,status').maybeSingle(); if(error||!data)return json({error:error?.message??'Rider application not found or already reviewed'},409); if(status==='approved')await service.from('profiles').update({role:'rider'}).eq('id',data.applicant_id); else await service.from('profiles').update({role:'customer'}).eq('id',data.applicant_id); await service.from('notifications').insert({user_id:data.applicant_id,type:'application',title:'Rider application update',body:`Your rider application is ${status}.`,data:{application_id:id,status}}); return json({ok:true,type,action,data});} return json({error:'Invalid rider action'},400);}
 if(action==='cancel'){const {data,error}=await service.from('orders').update({status:'cancelled'}).eq('id',id).in('status',['placed','restaurant_notified','accepted','preparing']).select('id,status').maybeSingle(); if(error||!data)return json({error:error?.message??'Order cannot be cancelled'},409); return json({ok:true,type,action,data});}
 return json({error:'Unsupported action'},400);
});
