import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { distanceKm } from '../_shared/geofence.ts';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}; const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); if(req.method!=='POST')return json({error:'Method not allowed'},405); const service=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!); const auth=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:req.headers.get('Authorization')??''}}}); const {data:{user}}=await auth.auth.getUser(); if(!user)return json({error:'Authentication required'},401);
 const body=await req.json().catch(()=>null); if(!body?.order_id)return json({error:'order_id is required'},400); const {data:order,error}=await service.from('orders').select('id,customer_id,restaurant_id,rider_id,status,delivery_address,delivery_latitude,delivery_longitude,created_at,accepted_at,picked_up_at,delivered_at').eq('id',body.order_id).maybeSingle(); if(error)return json({error:error.message},500); if(!order)return json({error:'Order not found'},404);
 const {data:restaurant}=await service.from('restaurants').select('id,name,address,latitude,longitude,owner_id').eq('id',order.restaurant_id).maybeSingle(); const allowed=order.customer_id===user.id||order.rider_id===user.id||restaurant?.owner_id===user.id; if(!allowed)return json({error:'Not allowed'},403);
 let rider_location=null, rider_metrics=null; if(order.rider_id){const {data:loc}=await service.from('rider_locations').select('latitude,longitude,accuracy_m,heading,updated_at,is_online').eq('rider_id',order.rider_id).maybeSingle(); rider_location=loc??null; if(loc){const ageSeconds=Math.max(0,Math.round((Date.now()-new Date(loc.updated_at).getTime())/1000)); const customerLat=Number(order.delivery_latitude),customerLng=Number(order.delivery_longitude); const hasCustomer=Number.isFinite(customerLat)&&Number.isFinite(customerLng); const distanceToCustomerKm=hasCustomer?distanceKm(Number(loc.latitude),Number(loc.longitude),customerLat,customerLng):null; rider_metrics={location_age_seconds:ageSeconds,distance_to_customer_km:distanceToCustomerKm===null?null:Number(distanceToCustomerKm.toFixed(2)),eta_minutes:distanceToCustomerKm===null?null:Math.max(1,Math.ceil(distanceToCustomerKm/25*60)),stale:ageSeconds>45};}}
 return json({order,restaurant:restaurant?{id:restaurant.id,name:restaurant.name,address:restaurant.address,latitude:restaurant.latitude,longitude:restaurant.longitude}:null,rider_location,rider_metrics});
});
