import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { isInBarmer } from '../_shared/geofence.ts';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}; const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const transitions:Record<string,string[]>={restaurant:['accepted','preparing','ready_for_pickup'],rider:['picked_up','on_the_way','delivered'],customer:['cancelled']};
const allowed:Record<string,string[]>={accepted:['restaurant_notified','placed'],preparing:['accepted'],ready_for_pickup:['preparing'],picked_up:['ready_for_pickup','rider_assigned'],on_the_way:['picked_up'],delivered:['on_the_way'],cancelled:['placed','restaurant_notified','accepted']};
const distanceKm=(a:number,b:number,c:number,d:number)=>{const R=6371,rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,q=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q));};
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); if(req.method!=='POST')return json({error:'Method not allowed'},405); const service=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!); const auth=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:req.headers.get('Authorization')??''}}}); const {data:{user}}=await auth.auth.getUser(); if(!user)return json({error:'Authentication required'},401);
 const body=await req.json().catch(()=>null); if(!body?.order_id||!body?.status)return json({error:'order_id and status are required'},400); const {data:profile}=await service.from('profiles').select('role').eq('id',user.id).maybeSingle(); const role=profile?.role as string|undefined; if(!role||!transitions[role]?.includes(body.status))return json({error:'Action not allowed'},403);
 const {data:order}=await service.from('orders').select('id,status,restaurant_id,rider_id,customer_id').eq('id',body.order_id).maybeSingle(); if(!order)return json({error:'Order not found'},404); if(role==='customer'&&order.customer_id!==user.id)return json({error:'Customer access denied'},403);
 if(role==='restaurant'){const {data:owned}=await service.from('restaurants').select('id').eq('id',order.restaurant_id).eq('owner_id',user.id).eq('is_approved',true).maybeSingle();if(!owned)return json({error:'Restaurant access denied'},403);} if(role==='rider'&&order.rider_id!==user.id)return json({error:'Order is not assigned to this rider'},403); if(!allowed[body.status]?.includes(order.status))return json({error:`Invalid transition from ${order.status}`},409);
 const patch:Record<string,unknown>={status:body.status}; if(body.status==='accepted')patch.accepted_at=new Date().toISOString(); if(body.status==='picked_up')patch.picked_up_at=new Date().toISOString(); if(body.status==='delivered')patch.delivered_at=new Date().toISOString();
 const {data:updated,error}=await service.from('orders').update(patch).eq('id',order.id).eq('status',order.status).select('id,status,customer_id,rider_id,restaurant_id').maybeSingle(); if(error||!updated)return json({error:'Order changed; please refresh'},409);
 const {data:restaurant}=await service.from('restaurants').select('owner_id,name,latitude,longitude').eq('id',updated.restaurant_id).maybeSingle(); const recipients=[updated.customer_id,updated.rider_id,restaurant?.owner_id].filter(Boolean).filter((id)=>id!==user.id); const unique=[...new Set(recipients)]; let warning;
 if(unique.length){const {error:e}=await service.from('notifications').insert(unique.map((user_id)=>({user_id,order_id:order.id,type:'order',title:body.status==='cancelled'?'ऑर्डर रद्द':'ऑर्डर अपडेट',body:body.status==='cancelled'?'ऑर्डर रद्द कर दिया गया है।':`ऑर्डर की स्थिति: ${body.status}`,data:{status:body.status}})));if(e)warning='Status updated but notification failed';}
 if(body.status==='ready_for_pickup'&&Number.isFinite(Number(restaurant?.latitude))&&Number.isFinite(Number(restaurant?.longitude))&&isInBarmer(Number(restaurant.latitude),Number(restaurant.longitude))){const cutoff=new Date(Date.now()-2*60*1000).toISOString(); const {data:riders}=await service.from('rider_locations').select('rider_id,latitude,longitude').eq('is_online',true).gte('updated_at',cutoff).limit(200); const ids=[...new Set((riders??[]).map((r:any)=>r.rider_id))]; if(ids.length){const {data:approved}=await service.from('rider_applications').select('applicant_id').eq('status','approved').in('applicant_id',ids); const approvedIds=new Set((approved??[]).map((r:any)=>r.applicant_id)); const lat=Number(restaurant.latitude),lng=Number(restaurant.longitude); const candidates=(riders??[]).filter((r:any)=>approvedIds.has(r.rider_id)&&isInBarmer(Number(r.latitude),Number(r.longitude))).map((r:any)=>({...r,km:distanceKm(lat,lng,Number(r.latitude),Number(r.longitude))})).filter((r:any)=>r.km<=15).sort((a:any,b:any)=>a.km-b.km); if(candidates.length){const {error:e}=await service.from('notifications').insert(candidates.map((r:any)=>({user_id:r.rider_id,order_id:order.id,type:'delivery_job',title:'🛵 नया delivery job',body:`${restaurant.name||'Restaurant'} से pickup — ${r.km.toFixed(1)} km दूर`,data:{status:'ready_for_pickup',distance_km:Number(r.km.toFixed(2))}})));if(e)warning='Rider notification failed';}}}
 return json({ok:true,order_id:updated.id,status:updated.status,...warning?{warning}:{} });
});
