-- Barmer Food Delivery marketplace expansion
create table if not exists public.payment_transactions(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,provider text not null default 'test',provider_payment_id text,amount numeric(10,2) not null check(amount>=0),status text not null default 'created' check(status in ('created','pending','paid','failed','refunded')),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists uq_payment_provider_id on public.payment_transactions(provider,provider_payment_id) where provider_payment_id is not null;
create table if not exists public.coupons(id uuid primary key default gen_random_uuid(),code text unique not null,description text,discount_type text not null check(discount_type in ('percent','flat')),discount_value numeric(10,2) not null check(discount_value>0),min_order_amount numeric(10,2) not null default 0, max_discount numeric(10,2),usage_limit int,used_count int not null default 0,active boolean not null default true,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.order_discounts(id uuid primary key default gen_random_uuid(),order_id uuid unique not null references public.orders(id) on delete cascade,coupon_id uuid references public.coupons(id) on delete set null,code text,discount_amount numeric(10,2) not null check(discount_amount>=0),created_at timestamptz not null default now());
alter table public.orders add column if not exists discount_amount numeric(10,2) not null default 0;
alter table public.orders add column if not exists payment_status text not null default 'pending' check(payment_status in ('pending','paid','failed','refunded','cod'));
create table if not exists public.kcy_documents(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,application_type text not null check(application_type in ('restaurant','rider')),document_type text not null,storage_path text not null,status text not null default 'pending' check(status in ('pending','approved','rejected')),admin_note text,created_at timestamptz not null default now(),reviewed_at timestamptz,unique(user_id,application_type,document_type));
-- Backward-compatible alias table name retained for deployments that already consumed the original schema.
create table if not exists public.payouts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete restrict,role public.app_role not null,amount numeric(10,2) not null check(amount>=0),status text not null default 'pending' check(status in ('pending','processing','paid','failed')),reference text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),paid_at timestamptz);
create table if not exists public.support_tickets(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,order_id uuid references public.orders(id) on delete set null,subject text not null,message text not null,status text not null default 'open' check(status in ('open','in_progress','resolved','closed')),priority text not null default 'normal' check(priority in ('low','normal','high','urgent')),admin_note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists idx_payment_order on public.payment_transactions(order_id,created_at desc); create index if not exists idx_coupon_active on public.coupons(active,starts_at,ends_at); create index if not exists idx_payout_user on public.payouts(user_id,created_at desc); create index if not exists idx_support_user on public.support_tickets(user_id,created_at desc); create index if not exists idx_audit_created on public.audit_logs(created_at desc);
alter table public.payment_transactions enable row level security; alter table public.coupons enable row level security; alter table public.order_discounts enable row level security; alter table public.kcy_documents enable row level security; alter table public.payouts enable row level security; alter table public.support_tickets enable row level security; alter table public.audit_logs enable row level security;
create policy "users read own payments" on public.payment_transactions for select using(auth.uid()=user_id);
create policy "public read active coupons" on public.coupons for select using(active=true and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>=now()));
create policy "customers read own discounts" on public.order_discounts for select using(exists(select 1 from public.orders o where o.id=order_id and o.customer_id=auth.uid()));
create policy "users read own kyc" on public.kcy_documents for select using(auth.uid()=user_id); create policy "users create own kyc" on public.kcy_documents for insert with check(auth.uid()=user_id);
create policy "users read own payouts" on public.payouts for select using(auth.uid()=user_id);
create policy "users read own support" on public.support_tickets for select using(auth.uid()=user_id); create policy "users create support" on public.support_tickets for insert with check(auth.uid()=user_id);
-- Admin/service-role writes are intentionally not exposed through client RLS policies.
